### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sandeepnRES** [rosewang2008/rmaddpg#1]
I was trying to reproduce your results, but got error while running:

```
Traceback (most recent call last):
  File "train.py", line 353, in <module>
    train(arglist)
  File "train.py", line 200, in train
    action_n = [agent.action(obs) for agent, obs in zip(trainers,obs_n)]
  File "train.py", line 200, in <listcomp>
    action_n = [agent.action(obs) for agent, obs in zip(trainers,obs_n)]
  File "/workspace/rmaddpg/maddpg/maddpg/trainer/rmaddpg.py", line 764, in action
    action, state = self.act(*[obs[None], self.p_c, self.p_h])
  File "/workspace/rmaddpg/maddpg/maddpg/common/tf_util.py", line 318, in __call__
    results = get_session().run(self.outputs_update, feed_dict=feed_dict)[:-1]
  File "/workspace/.pip-modules/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 10) for Tensor 'observation0:0', which has shape '(?, 1, 10)'
```

To reproduce this error, run:

`python3 train.py --scenario simple_push --actor-lstm --critic-lstm`

**Comment by rosewang2008** [comment]
Hi, Apologies for not seeing this earlier. It was a tensor dimensional error that was not properly versioned with what I had locally. You should be able to train now without that error. 

Feel free to open this issue if there are any additional problems.
