### ISSUE TITLE
TypeError: object of type 'numpy.float64' has no len()

### ISSUE THREAD

**Issue by xzxgg** [rosewang2008/rmaddpg#2]
using:python3.7
tensorfllow1.14.0
gym 0.10.5
2020-08-06 17:05:30.830852: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "C:/Users/zym/Desktop/多车二维代码/MADDPG/rmaddpg-master/maddpg/experiments/train.py", line 354, in <module>
    train(arglist)
  File "C:/Users/zym/Desktop/多车二维代码/MADDPG/rmaddpg-master/maddpg/experiments/train.py", line 151, in train
    env = make_env(arglist.scenario, arglist, arglist.benchmark)
  File "C:/Users/zym/Desktop/多车二维代码/MADDPG/rmaddpg-master/maddpg/experiments/train.py", line 100, in make_env
    env = MultiAgentEnv(world, scenario.reset_world, rewards.sim_higher_arrival_reward,  scenario.observation)
  File "C:\Users\zym\Desktop\多车二维代码\MADDPG\rmaddpg-master\multiagent-particle-envs\multiagent\environment.py", line 68, in __init__
    obs_dim = len(observation_callback(agent, self.world)[0]) # edited
TypeError: object of type 'numpy.float64' has no len()

**Comment by Geniusddd** [comment]
> using:python3.7 tensorfllow1.14.0 gym 0.10.5 2020-08-06 17:05:30.830852: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 Traceback (most recent call last): File "C:/Users/zym/Desktop/多车二维代码/MADDPG/rmaddpg-master/maddpg/experiments/train.py", line 354, in train(arglist) File "C:/Users/zym/Desktop/多车二维代码/MADDPG/rmaddpg-master/maddpg/experiments/train.py", line 151, in train env = make_env(arglist.scenario, arglist, arglist.benchmark) File "C:/Users/zym/Desktop/多车二维代码/MADDPG/rmaddpg-master/maddpg/experiments/train.py", line 100, in make_env env = MultiAgentEnv(world, scenario.reset_world, rewards.sim_higher_arrival_reward, scenario.observation) File "C:\Users\zym\Desktop\多车二维代码\MADDPG\rmaddpg-master\multiagent-particle-envs\multiagent\environment.py", line 68, in **init** obs_dim = len(observation_callback(agent, self.world)[0]) # edited TypeError: object of type 'numpy.float64' has no len()

Don't use the multiagent folder provided by him. Go to github to search the multiagent folder
